### ISSUE TITLE
Button names in libinput config

### ISSUE THREAD

**Issue by emersion** [swaywm/sway#3278]
`libevdev_get_event_code_name` can parse button names.

Source: https://gitlab.freedesktop.org/wayland/weston/merge_requests/66#note_87331

**Comment by RedSoxFan** [comment]
Once the following PRs are merged, this can be closed:
- [ ] #3341 - Improve mouse button parsing: helpers and bind{code,sym}
- [ ] #3342 - Improve mouse button parsing: input scroll_button
- [ ] #3343 - Improve mouse button parsing: seat cursor
- [ ] #3344 - Improve mouse button parsing: bar bind{code,sym}
