### ISSUE TITLE
HiDPI support meta-issue

### ISSUE THREAD

**Issue by SirCmpwn** [swaywm/sway#797]
- [x] Specify scale in output command
- [x] Pass scale factor to wlc
- [x] Screenshots
- [x] Client-side support
  - [x] swaybg
  - [x] swaybar
  - [x] swaylock
- [x] Window borders
- [x] swaybg given the wrong size on the screen
- [x] gaps

**Comment by Hummer12007** [comment]
Gaps are 2x bigger on hidpi (should be scaled).

**Comment by SirCmpwn** [comment]
Client-side support done as of https://github.com/SirCmpwn/sway/compare/0913eff9157a...af441541197a

**Comment by mlofjard** [comment]
I get mouse cursor size issues when adding scale 2x to my config. On the title bar and background surfaces the mouse cursor is really tiny (not scaled at all), and in urxvt or weston-terminal (i.e. both wayland and xwayland apps) the mouse cursor is 4x the size. I dont get the correct size of the cursor anywhere.

**Comment by ametisf** [comment]
I have mouse cursor scale issues without any scaling specified in my config. Above Qt clients (qutebrowser, qtcreator) it appears double the expected size, anything not-Qt is ok (xterm, wlterm, chromium, firefox).

**Comment by william01110111** [comment]
Programs running in XWayland are scaled correctly, but this is done (presumably) by rendering them at a low resolution and scaling them up because they are all low res and bury. A better solution would be to render them at full resolution with the proper HiDPI X11 settings or even have some mechanism to choose between the two options (since not everything works well on HiDPI). I know this is possible because Gnome does it and everything looks great. I'm willing to help implement this if you point me in the right direction.

**Comment by handijk** [comment]
Choosing between the two options does not seem possible, see: https://github.com/Enerccio/ewlc/issues/82
I have created an issue to allow for setting a global DPI for xwayland in ewlc, see: https://github.com/Enerccio/ewlc/issues/99

**Comment by SirCmpwn** [comment]
Note that sway doesn't use ewlc. If you'd like to see XWayland DPI improvements in Sway, they should be submitted to wlc.

**Comment by Enerccio** [comment]
@SirCmpwn sway can be build with ewlc (tested):

   cmake -DWLC_LIBRARIES=<ewlc-path>/target/src/libewlc.so -DWLC_INCLUDE_DIRS=<ewlc-path>/include ..

**Comment by SirCmpwn** [comment]
That doesn't surprise me, but we're still not switching right now.

**Comment by Enerccio** [comment]
Of course, I mean more in a way that optionally someone can do it themselves

**Comment by handijk** [comment]
I have submitted an issue to wlc also, https://github.com/Cloudef/wlc/issues/268

**Comment by Hummer12007** [comment]
Gnome is planning to implement fractional scaling: https://blogs.gnome.org/mclasen/2017/05/19/fractional-scaling-goes-east/

**Comment by rightaway** [comment]
If I have a hiDPI screen I need to use the hidpi branch? On https://github.com/swaywm/sway/wiki it says that I can use that setting for hiDPI support in sway, so what's the difference between using the main release with that setting vs the hidpi branch?

**Comment by SirCmpwn** [comment]
The hidpi branch was merged, just use stable releases.

**Comment by main--** [comment]
By the way, I would love to have a way that disables all upscaling of non-highdpi-aware applications while still correctly telling the others about scale factors and scaling them down on non-highdpi displays (what you described in swaywm/wlroots#329).

Right now I have highdpi disabled even for my 4k monitor because I strongly prefer hard-to-read over blurry.

**Comment by gnidorah** [comment]
How about fractional values for scaling? 2x is too much for e.g. 12.5" fullhd, 1x is too low.

**Comment by likyng** [comment]
Would it be possible that sway renders xwayland windows at 1x, even if scale=2 is set in the sway config? Then, scaling could be set within x11 so that xwayland windows (with scaling support) will be rendered crisply?

**Comment by SirCmpwn** [comment]
This is done :tada:
